Adapt OR and AND checks to the new '*value*' check
That is needed to fix these assertions:
```
  File "/home/a13x/land/develop/Linux_Kernel/kernel-hardening-checker/kernel_hardening_checker/engine.py", line 302, in check
    assert(opt.result.startswith('OK: is not off')), \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: unexpected OK description "OK: in "lockdown,yama,integrity,apparmor,bpf,landlock""
```
and
```
  File "/home/a13x/land/develop/Linux_Kernel/kernel-hardening-checker/kernel_hardening_checker/engine.py", line 340, in check
    assert(opt.result == 'FAIL: is off, not found'), \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: unexpected FAIL description "FAIL: not in "lockdown,yama,integrity,apparmor,bpf,landlock""
```